// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    SearchForm: typeof import('./src/components/SearchForm.vue')['default']
    SearchList: typeof import('./src/components/SearchList.vue')['default']
    SearchMore: typeof import('./src/components/SearchMore.vue')['default']
  }
}

export { }
